version: '3'

services:
  database-service:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
  api-service:
    depends_on:
      - database-service
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
